version: '3'

services:

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    restart: always
    volumes:
      - ./project:/srv/docker-server
      - ./project/static/:/static/
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    container_name: django
    build: ./project
    image: camp
    restart: always
    command: >
      bash -c "python3 manage.py collectstatic --noinput
      && gunicorn config.wsgi -b 0.0.0.0:8000 "
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./project:/srv/docker-server
      - ./log:/var/log/gunicorn

#
#volumes:
#  static: